// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package dataprotection.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;

public class JA_Entity_Count_WithXPath extends UserAction<java.lang.Long>
{
	private final java.lang.String EntityName;
	private final java.lang.String XPathConstraint;

	public JA_Entity_Count_WithXPath(
		IContext context,
		java.lang.String _entityName,
		java.lang.String _xPathConstraint
	)
	{
		super(context);
		this.EntityName = _entityName;
		this.XPathConstraint = _xPathConstraint;
	}

	@java.lang.Override
	public java.lang.Long executeAction() throws Exception
	{
		// BEGIN USER CODE
		final String xpath = dataprotection.impl.DataFakerImpl.buildXPath(EntityName, XPathConstraint);

		// Use XPath aggregate count via the fluent API
		final long total =
				com.mendix.core.Core
						.createXPathQuery("count(" + xpath + ")")
						.executeAggregateLong(getContext());

		return total;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_Entity_Count_WithXPath";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
