// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package dataprotection.actions;

import java.util.List;
import java.util.concurrent.ThreadLocalRandom;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.IMendixObjectMember;
import com.mendix.systemwideinterfaces.core.UserAction;
import dataprotection.impl.DataFakerImpl;

public class JA_ConfigurationEntity_ApplyRule_Batch extends UserAction<java.lang.Long>
{
	/** @deprecated use InputEntity.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __InputEntity;
	private final dataprotection.proxies.ConfigurationEntity InputEntity;
	private final java.lang.Long Offset;
	private final java.lang.Long BatchSize;
	private final java.lang.Boolean CommitWithoutEvents;

	public JA_ConfigurationEntity_ApplyRule_Batch(
		IContext context,
		IMendixObject _inputEntity,
		java.lang.Long _offset,
		java.lang.Long _batchSize,
		java.lang.Boolean _commitWithoutEvents
	)
	{
		super(context);
		this.__InputEntity = _inputEntity;
		this.InputEntity = _inputEntity == null ? null : dataprotection.proxies.ConfigurationEntity.initialize(getContext(), _inputEntity);
		this.Offset = _offset;
		this.BatchSize = _batchSize;
		this.CommitWithoutEvents = _commitWithoutEvents;
	}

	@java.lang.Override
	public java.lang.Long executeAction() throws Exception
	{
		// BEGIN USER CODE
		final com.mendix.systemwideinterfaces.core.IContext ctx = getContext();
		final dataprotection.proxies.ConfigurationEntity cfgEntity = this.InputEntity;

		if (cfgEntity == null) {
			throw new IllegalArgumentException("ConfigurationEntity input is null (check field name in skeleton).");
		}

		final String entityName = trimToNull(cfgEntity.getEntityName());
		if (entityName == null) {
			throw new IllegalArgumentException("ConfigurationEntity.EntityName is empty");
		}

		final dataprotection.proxies.ConfigurationSet cfgSet = cfgEntity.getConfigurationEntity_ConfigurationSet(); // Parent config set (for locale/deterministic)
		final String localeTag = (cfgSet != null) ? trimToNull(cfgSet.getDefaultLocale()) : null;		
		final String salt = getConstantStringOrEmpty("DataProtection.Salt"); // Salt comes from a constant
		final long offsetL = (this.Offset == null || this.Offset < 0L) ? 0L : this.Offset; // Offset / batch size are Long based
		final int offset = safeLongToInt(offsetL, "Offset");
		final long batchSizeL = (this.BatchSize == null || this.BatchSize <= 0L) ? 1000L : this.BatchSize;
		final int batchSize = safeLongToInt(batchSizeL, "BatchSize");
		final boolean commitWithoutEvents = (this.CommitWithoutEvents == null) ? true : this.CommitWithoutEvents;
		final java.util.List<dataprotection.proxies.ConfigurationAttribute> rules = new java.util.ArrayList<>(); // Load active rules for this entity via XPath

		final String ruleXpath =
				"//" + dataprotection.proxies.ConfigurationAttribute.entityName
			+ "[" + dataprotection.proxies.ConfigurationAttribute.MemberNames.ConfigurationAttribute_ConfigurationEntity
			+ " = " + cfgEntity.getMendixObject().getId().toLong() + "]"
			+ "[Active = true()]";

		final java.util.List<com.mendix.systemwideinterfaces.core.IMendixObject> ruleObjects =
				com.mendix.core.Core.retrieveXPathQuery(ctx, ruleXpath);

		for (com.mendix.systemwideinterfaces.core.IMendixObject ro : ruleObjects) {
			rules.add(dataprotection.proxies.ConfigurationAttribute.initialize(ctx, ro));
		}

		if (rules.isEmpty()) {
			return 0L;
		}

		final String xpath = buildXPath(entityName, cfgEntity.getXPathConstraint()); // Build XPath and retrieve batch
		final List<IMendixObject> objects =
    		com.mendix.core.Core.retrieveXPathQuery(ctx, xpath, batchSize, offset, java.util.Collections.emptyMap());

		if (objects.isEmpty()) {
			return 0L;
		}

		// Apply rules
		final java.util.Map<String, ShuffleBucket> shuffleBuckets = new java.util.HashMap<>();
		final java.util.Set<com.mendix.systemwideinterfaces.core.IMendixObject> changedObjects = new java.util.HashSet<>();
		final java.util.Set<String> usedUnique = new java.util.HashSet<>();

		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : objects) {

			for (dataprotection.proxies.ConfigurationAttribute rule : rules) {
				final String attrName = trimToNull(rule.getAttributeName());
				if (attrName == null) continue;

				final com.mendix.systemwideinterfaces.core.IMendixObjectMember<?> member = safeGetMember(obj, attrName);
				if (member == null) continue;

				final dataprotection.proxies.Enum_RuleType ruleType = rule.getRuleType();
				if (ruleType == null) continue;

				// 1) SHUFFLE is handled in a second pass
				if (ruleType == dataprotection.proxies.Enum_RuleType.SHUFFLE) {
					final Object originalValue = member.getValue(ctx);
					if (isEmptyValue(originalValue)) {						
						continue; // empty stays empty
					}

					final boolean det = Boolean.TRUE.equals(rule.getDeterministic(ctx));
					final String bucketKey = obj.getType() + "|" + attrName; // per entity+attribute
					final ShuffleBucket bucket = shuffleBuckets.computeIfAbsent(
						bucketKey,
						k -> new ShuffleBucket(rule, attrName, det)
					);

					bucket.targets.add(obj);
					bucket.values.add(originalValue);
					continue;
				}

				// 2) Non-shuffle: apply immediately
				final Object newValue = generateValueForRule(
					ctx, obj, member, rule,
					localeTag,
					salt, usedUnique
				);

				if (newValue == KEEP_SENTINEL) continue;

				final Object typedValue = coerceToMemberType(member, newValue);
				obj.setValue(ctx, member.getName(), typedValue);
				changedObjects.add(obj);
			}
		}

		for (ShuffleBucket bucket : shuffleBuckets.values()) {
			if (bucket.values.size() <= 1) continue; // nothing to shuffle

			final java.util.List<Object> shuffled = new java.util.ArrayList<>(bucket.values);

			if (bucket.deterministic) {
				final String detInput = "SHUFFLE|" + bucket.targets.get(0).getType() + "|" + bucket.attrName;
				final long seed = deterministicSeed(salt, detInput);
				java.util.Collections.shuffle(shuffled, new java.util.Random(seed));
			} else {
				java.util.Collections.shuffle(shuffled);
			}

			for (int i = 0; i < bucket.targets.size(); i++) {
				final com.mendix.systemwideinterfaces.core.IMendixObject obj = bucket.targets.get(i);
				final com.mendix.systemwideinterfaces.core.IMendixObjectMember<?> member = safeGetMember(obj, bucket.attrName);
				if (member == null) continue;

				final Object typedValue = coerceToMemberType(member, shuffled.get(i));
				obj.setValue(ctx, member.getName(), typedValue);
				changedObjects.add(obj);
			}
		}

		// Commit
		final long changedCount = changedObjects.size();

		if (changedCount > 0L) {
			final java.util.List<com.mendix.systemwideinterfaces.core.IMendixObject> toCommit =
				new java.util.ArrayList<>(changedObjects);

			if (commitWithoutEvents) {
				com.mendix.core.Core.commitWithoutEvents(ctx, toCommit);
			} else {
				com.mendix.core.Core.commit(ctx, toCommit);
			}
		}

		return changedCount;

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_ConfigurationEntity_ApplyRule_Batch";
	}

	// BEGIN EXTRA CODE
	private static final Object KEEP_SENTINEL = new Object();

	private static String trimToNull(String s) {
		if (s == null) return null;
		String t = s.trim();
		return t.isEmpty() ? null : t;
	}

	private static int safeLongToInt(long v, String name) {
		if (v > Integer.MAX_VALUE) {
			throw new IllegalArgumentException(name + " is too large: " + v);
		}
		return (int) v;
	}

	private static String buildXPath(String entityName, String constraint) {
		final String base = "//" + entityName;
		final String c = (constraint == null) ? "" : constraint.trim();
		if (c.isEmpty()) return base;
		return c.startsWith("[") ? (base + c) : (base + "[" + c + "]");
	}

	private static com.mendix.systemwideinterfaces.core.IMendixObjectMember<?> safeGetMember(
			com.mendix.systemwideinterfaces.core.IMendixObject obj,
			String attrName
	) {
		try {
			return obj.getMember(attrName);
		} catch (Exception e) {
			return null;
		}
	}

	private static String getConstantStringOrEmpty(String fullyQualifiedConstantName) {
		try {
			Object v = com.mendix.core.Core.getConfiguration().getConstantValue(fullyQualifiedConstantName);
			return v == null ? "" : String.valueOf(v);
		} catch (Exception e) {
			return "";
		}
	}

	private static Object generateValueForRule(
			com.mendix.systemwideinterfaces.core.IContext ctx,
			com.mendix.systemwideinterfaces.core.IMendixObject obj,
			com.mendix.systemwideinterfaces.core.IMendixObjectMember<?> member,
			dataprotection.proxies.ConfigurationAttribute rule,
			String localeTag,
			String salt,
			java.util.Set<String> usedUnique
	) throws Exception {

		// Your RuleType enum is: KEEP, CLEAR, GENERATE, HASH, GENERALIZE
		final dataprotection.proxies.Enum_RuleType ruleType = rule.getRuleType();
		final boolean deterministic = Boolean.TRUE.equals(rule.getDeterministic(ctx));
		final boolean unique = Boolean.TRUE.equals(rule.getUnique());

		if (ruleType == dataprotection.proxies.Enum_RuleType.GENERATE && deterministic && unique) {
			throw new IllegalArgumentException(
				"GENERATE rule cannot be both deterministic and unique for attribute " + rule.getAttributeName()
			);
		}

		final Object originalValue = member.getValue(ctx);
		final boolean isEmpty =
			originalValue == null ||
			(originalValue instanceof String && ((String) originalValue).trim().isEmpty());

		final Long seed;
		if (deterministic && !isEmpty) {
			final String detInput = member.getName() + "=" + originalValue.toString(); // value-based determinism, stable across env/imports
			seed = deterministicSeed(salt, detInput);
		} else {
			seed = null;
		}

		if (ruleType == null) return KEEP_SENTINEL;

		switch (ruleType) {
			case KEEP:
				return KEEP_SENTINEL;

			case CLEAR:
				return null;

			case FIXED: {
				final String fixedValue = trimToNull(rule.getFixedValue());
				return coerceToMemberType(member, fixedValue);
			}

			case HASH: {				
				if (isEmpty) {
					return originalValue; // null or ""
				}

				final String token = deterministic
						? "DP_" + Long.toHexString(seed)
						: "DP_" + Long.toHexString(ThreadLocalRandom.current().nextLong());

				return coerceToMemberType(member, token);
			}

			case GENERALIZE: {
				final dataprotection.proxies.Enum_GeneralizeLevel level = rule.getGeneralizeLevel();
				final Object generalized = generalize(member.getValue(ctx), level);
				return coerceToMemberType(member, generalized);
			}

			case GENERATE: {
				if (isEmpty) {
					return originalValue;
				}

				final dataprotection.proxies.Enum_GenerationMethod gm = rule.getGenerationMethod(); // your GenerateMode enum
				if (gm == null) {
					throw new IllegalArgumentException("Generate Mode is null for attribute " + rule.getAttributeName());
				}

				final String input = trimToNull(rule.getTemplateExpression());
				if (input == null) {
					throw new IllegalArgumentException("Input is empty for attribute " + rule.getAttributeName());
				}

				final String generated = generateWithFaker(
						input,
						gm,
						localeTag,
						seed
				);

				final String out = unique
						? ensureUnique(rule.getAttributeName(), generated, originalValue.toString(), usedUnique)
						: generated;

				return coerceToMemberType(member, out);
			}

			default:
				throw new IllegalArgumentException("Unsupported RuleType: " + ruleType);
		}
	}

	private static String generateWithFaker(
			String input,
			dataprotection.proxies.Enum_GenerationMethod gm,
			String localeTag,
			Long seed
	) throws Exception {
    	return DataFakerImpl.generate(input, gm, localeTag, seed);
	}

	private static String ensureUnique(String attrName, String value, String objectId, java.util.Set<String> used) {
		final String base = (value == null) ? "" : value;
		String candidate = base;
		int tries = 0;

		while (used.contains(attrName + "|" + candidate)) {
			tries++;
			String suffix = objectId;
			if (suffix.length() > 6) suffix = suffix.substring(suffix.length() - 6);
			candidate = base + "_" + suffix + "_" + tries;
			if (tries > 25) break;
		}
		used.add(attrName + "|" + candidate);
		return candidate;
	}

	private static Object coerceToMemberType(
			com.mendix.systemwideinterfaces.core.IMendixObjectMember<?> member,
			Object newValue
	) {
		if (newValue == null) return null;

		// Already “safe” types for Mendix attribute values
		if (newValue instanceof String) return newValue;
		if (newValue instanceof Boolean) return newValue;
		if (newValue instanceof java.util.Date) return newValue;
		if (newValue instanceof java.math.BigDecimal) return newValue;

		// Numbers: Mendix numeric members typically accept Long / BigDecimal.
		// Return Long by default (safe for Integer/Long-like attributes).
		if (newValue instanceof Number) {
			return ((Number) newValue).longValue();
		}

		// Enums are usually stored as their string key in Mendix Java API
		// If callers pass an enum instance, store its name.
		if (newValue instanceof Enum<?>) {
			return ((Enum<?>) newValue).name();
		}

		// Fallback: store as string (safe for String-like members; others will throw on set)
		return String.valueOf(newValue);
	}


	private static Object generalize(Object currentValue, dataprotection.proxies.Enum_GeneralizeLevel level) {
		if (currentValue == null) return null;
		if (level == null) return currentValue;

		if (currentValue instanceof java.util.Date d) {
			java.util.Calendar cal = java.util.Calendar.getInstance(java.util.TimeZone.getTimeZone("UTC"));
       		cal.setTime(d);
			cal.set(java.util.Calendar.HOUR_OF_DAY, 12);
			cal.set(java.util.Calendar.MINUTE, 0);
			cal.set(java.util.Calendar.SECOND, 0);
			cal.set(java.util.Calendar.MILLISECOND, 0);

			switch (level) {
				case YEAR:
					cal.set(java.util.Calendar.MONTH, 0);
					cal.set(java.util.Calendar.DAY_OF_MONTH, 1);
					return cal.getTime();
				case YEAR_MONTH:
					cal.set(java.util.Calendar.DAY_OF_MONTH, 1);
					return cal.getTime();
				case DATE_ONLY:
					return cal.getTime();
				default:
					return d;
			}
		}

		return currentValue;
	}

	private static long deterministicSeed(String salt, String detInput) {
		final String s = (salt == null ? "" : salt) + "|" + detInput;
		try {
			final java.security.MessageDigest md = java.security.MessageDigest.getInstance("SHA-256");
			final byte[] h = md.digest(s.getBytes(java.nio.charset.StandardCharsets.UTF_8));
			long out = 0L;
			for (int i = 0; i < 8; i++) out = (out << 8) | (h[i] & 0xffL);
			return out;
		} catch (Exception e) {
			return s.hashCode();
		}
	}

	private static final class ShuffleBucket {
		final dataprotection.proxies.ConfigurationAttribute rule;
		final String attrName;
		final boolean deterministic;
		final java.util.List<com.mendix.systemwideinterfaces.core.IMendixObject> targets = new java.util.ArrayList<>();
		final java.util.List<Object> values = new java.util.ArrayList<>();

		ShuffleBucket(dataprotection.proxies.ConfigurationAttribute rule, String attrName, boolean deterministic) {
			this.rule = rule;
			this.attrName = attrName;
			this.deterministic = deterministic;
		}
	}

	private static boolean isEmptyValue(Object v) {
		if (v == null) return true;
		if (v instanceof String s) return s.trim().isEmpty();
		return false;
	}
	// END EXTRA CODE
}
