// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package dataprotection.actions;

import java.util.ArrayList;
import java.util.List;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import dataprotection.impl.DataFakerImpl;
import dataprotection.proxies.SeedSource;

public class JA_DeterministicSeed_Generate extends UserAction<java.lang.Long>
{
	/** @deprecated use com.mendix.utils.ListUtils.map(SeedSourceList, com.mendix.systemwideinterfaces.core.IEntityProxy::getMendixObject) instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final java.util.List<IMendixObject> __SeedSourceList;
	private final java.util.List<dataprotection.proxies.SeedSource> SeedSourceList;

	public JA_DeterministicSeed_Generate(
		IContext context,
		java.util.List<IMendixObject> _seedSourceList
	)
	{
		super(context);
		this.__SeedSourceList = _seedSourceList;
		this.SeedSourceList = java.util.Optional.ofNullable(_seedSourceList)
			.orElse(java.util.Collections.emptyList())
			.stream()
			.map(seedSourceListElement -> dataprotection.proxies.SeedSource.initialize(getContext(), seedSourceListElement))
			.collect(java.util.stream.Collectors.toList());
	}

	@java.lang.Override
	public java.lang.Long executeAction() throws Exception
	{
		// BEGIN USER CODE
		if (this.SeedSourceList == null || this.SeedSourceList.isEmpty()) {
			throw new IllegalArgumentException(
				"SeedSources list is empty. At least one SeedSource value is required to generate a deterministic seed."
			);
		}
		
		List<String> parts = new ArrayList<>();

        if (this.SeedSourceList != null) {
            for (SeedSource src : this.SeedSourceList) {
                if (src == null) continue;
                
                String value = src.getValue();
                parts.add(value == null ? "" : value);
            }
        }

        return DataFakerImpl.deterministicSeed(parts.toArray(new String[0]));
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_DeterministicSeed_Generate";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
