// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package dataprotection.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;
import net.datafaker.Faker;
import java.util.Locale;
import java.util.Random;
import dataprotection.impl.DataFakerImpl;

public class JA_DataFaker_Generate extends UserAction<java.lang.String>
{
	private final dataprotection.proxies.Enum_GenerationMethod Mode;
	private final java.lang.String Input;
	private final java.lang.String Locale;
	private final java.lang.Long Seed;

	public JA_DataFaker_Generate(
		IContext context,
		java.lang.String _mode,
		java.lang.String _input,
		java.lang.String _locale,
		java.lang.Long _seed
	)
	{
		super(context);
		this.Mode = _mode == null ? null : dataprotection.proxies.Enum_GenerationMethod.valueOf(_mode);
		this.Input = _input;
		this.Locale = _locale;
		this.Seed = _seed;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		return DataFakerImpl.generate(
				this.Input,
				this.Mode,
				this.Locale,
				this.Seed
		);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_DataFaker_Generate";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
