// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxbluecommons.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Capitalized the first X characters, depending on "numberOfChars" parameter.
 */
public class CapitalizeFirstCharacters extends UserAction<java.lang.String>
{
	private final java.lang.Long numberOfChars;
	private final java.lang.String inputString;

	public CapitalizeFirstCharacters(
		IContext context,
		java.lang.Long _numberOfChars,
		java.lang.String _inputString
	)
	{
		super(context);
		this.numberOfChars = _numberOfChars;
		this.inputString = _inputString;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		String res = this.inputString;
		Integer len = inputString.length();

		// Check length.
        if (len > this.numberOfChars) {
            
            // Capitalize first char(s).
            res = this.inputString.substring(0, this.numberOfChars.intValue()).toUpperCase() + this.inputString.substring(this.numberOfChars.intValue());
        } else {
            
            // Capitalize all chars.
            res = this.inputString.toUpperCase();
        }

		// Return 
		return res;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CapitalizeFirstCharacters";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
