// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxbluecommons.actions;

import com.google.zxing.BarcodeFormat;
import com.google.zxing.WriterException;
import com.google.zxing.client.j2se.MatrixToImageWriter;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.qrcode.QRCodeWriter;
import java.io.ByteArrayOutputStream;
import java.util.Base64;import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Create a QR code. The actions returns a base64 string of the created PNG.
 */
public class CreateQRCode extends UserAction<java.lang.String>
{
	private final java.lang.String QRCodeValue;
	private final java.lang.Long Width;
	private final java.lang.Long Height;

	public CreateQRCode(
		IContext context,
		java.lang.String _qRCodeValue,
		java.lang.Long _width,
		java.lang.Long _height
	)
	{
		super(context);
		this.QRCodeValue = _qRCodeValue;
		this.Width = _width;
		this.Height = _height;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		//throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		
		// Create qr code writer.
		QRCodeWriter qrCodeWriter = new QRCodeWriter();
    	
		// Get BitMatrix
    	BitMatrix bitMatrix = qrCodeWriter.encode(this.QRCodeValue, BarcodeFormat.QR_CODE, this.Width.intValue(), this.Height.intValue());
    
    	// Create output stream.
    	ByteArrayOutputStream pngOutputStream = new ByteArrayOutputStream();
    	
    	// Write bitmatrix to output stream.
    	MatrixToImageWriter.writeToStream(bitMatrix, "PNG", pngOutputStream);

    	// Get byte array.
    	byte[] pngData = pngOutputStream.toByteArray(); 

    	// Return Base64 encoded string.
    	return Base64.getEncoder().encodeToString(pngOutputStream.toByteArray());

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CreateQRCode";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
