// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxbluecommons.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import java.util.ArrayList;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Get all first chars from words in a text. Choose whether the chars should be capitalized and what seperator should be used when putting the chars together. Great for getting initials from a name.
 * 
 * Using a seperator "." and using capitalize=true this will result in:
 * John Doe => J.D.
 * Save our souls => S.O.S.
 */
public class FirstCharsFromWordsInText extends UserAction<java.lang.String>
{
	private final java.lang.String inputString;
	private final java.lang.String seperator;
	private final java.lang.Boolean capitalize;

	public FirstCharsFromWordsInText(
		IContext context,
		java.lang.String _inputString,
		java.lang.String _seperator,
		java.lang.Boolean _capitalize
	)
	{
		super(context);
		this.inputString = _inputString;
		this.seperator = _seperator;
		this.capitalize = _capitalize;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		String res = this.inputString;
		String[] splitted = res.split("\\s+");
		ArrayList<String> chars = new ArrayList<String>();
		String split = null;

		// Loop through splitted.        
        for(int i = 0; i < splitted.length; i++) {

        	// Check for IJ, as in IJmuiden, IJs.
            if (splitted[i].length() > 1 && splitted[i].substring(0,2).toLowerCase().equals("ij")) {
                split = splitted[i].substring(0,2);    
            } else {
                split = splitted[i].substring(0,1);
            } 
            
            // Add to list.
            if (this.capitalize) {
            	chars.add(split.toUpperCase());	
            } else {
            	chars.add(split);
            }
        }
        
        // Set result.
        res = String.join(seperator, chars) + seperator;

		// Return.
		return res;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "FirstCharsFromWordsInText";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
