// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxbluecommons.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import org.apache.commons.lang3.StringUtils;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Generate a random code with characters you want. Nice to use when you want eliminate characters that can be confusing, like 0 (zero), o, O or 8 and B or 1, i, I, l.
 * 
 * The string without the confusing characters:
 * 
 * abcdefghjkmnpqrstuvwxyzACDEFGHJKMNPQRSTUVWXYZ2345679
 * 
 * Use what ever characters you want.
 */
public class GenerateRandomString extends UserAction<java.lang.String>
{
	private final java.lang.String CharactersToUse;
	private final java.lang.Long LengthOfCode;

	public GenerateRandomString(
		IContext context,
		java.lang.String _charactersToUse,
		java.lang.Long _lengthOfCode
	)
	{
		super(context);
		this.CharactersToUse = _charactersToUse;
		this.LengthOfCode = _lengthOfCode;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE

		// Repeat the available characters to have more (random) choice.
		//String chars = this.CharactersToUse.repeat(100); <== not available in Mx7
		String chars = StringUtils.repeat(this.CharactersToUse, 100);
		
		// The code to be generated.
		String code = "";

		// Add chars to the maximum length.
		for(int ix=1; ix<= this.LengthOfCode; ix++) {
			
			// Determine random location/index of the available characters.
			int loc = (int)(Math.random() * (chars.length() - 1) + 1);

			// Get character and add to code.
			code = code + chars.substring(loc, loc + 1);
		}

		// Return code, you'll need it.
		return code;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GenerateRandomString";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
