// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxbluecommons.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import java.util.Stack;
import com.mendix.core.*;
import com.mendix.systemwideinterfaces.core.ICoreAction; 
import com.mendix.systemwideinterfaces.core.UserAction;

public class GetCurrentMicroflow extends UserAction<java.lang.String>
{
	private final java.lang.Long Level;

	public GetCurrentMicroflow(
		IContext context,
		java.lang.Long _level
	)
	{
		super(context);
		this.Level = _level;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		// ==> CoreAction was replaced by ICoreAction <== //
		String mfName = "";
		IContext context = this.getContext();
		Stack<ICoreAction<?>> coreAction;
		ICoreAction<?> nthCoreAction;
		
		// Determine level.
		int intLevel = this.Level != null ? this.Level.intValue() : 1;

		if (context != null) {

			// Get action stack.
			coreAction = context.getActionStack();

			// Do we have an action stack?
			if (coreAction != null) {

				// Determine stack size.
				int actionStackSize = coreAction.size();

				// Determine the level in the stack.
				int intLevelStack = (actionStackSize - intLevel) - 1;

				// Check level in stack is within limits. (=> ArrayIndexOutOfBounds)
				if (intLevelStack >= 0 && intLevelStack < actionStackSize) {

					// Get action at stack level.
					nthCoreAction = coreAction.get(intLevelStack);

					// Do we have an action?
					if (nthCoreAction != null) {

						// Set microflow name (finally!)
						mfName = nthCoreAction.getActionName();
					}
				}
			}
		}

		// Return.
		return mfName;

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetCurrentMicroflow";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
