// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxbluecommons.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.core.conf.RuntimeVersion;
import com.mendix.systemwideinterfaces.core.UserAction;

public class GetRuntimeVersion extends UserAction<java.lang.String>
{
	public GetRuntimeVersion(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE

		// Get runtime version instance.
		RuntimeVersion runtimeVersion = RuntimeVersion.getInstance();
		
		// Return runtime version (as string).
		return runtimeVersion.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetRuntimeVersion";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
