// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxbluecommons.actions;

import com.mendix.core.Core;
import com.mendix.core.objectmanagement.DataValidationInfo;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import java.util.HashMap;
import java.util.Map;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Processes a Feedback message. Show a validation message when "OnScreen" is true, and logs a message in the console/log when "InConsole" is true.
 * 
 * When "OnScreen" is true, don't forget to add an entity! ;-)
 * 
 * Unfortunately no automatic translation of the feedback validation message.
 */
public class ProcessFeedbackMessage extends UserAction<java.lang.Void>
{
	/** @deprecated use FeedbackEntity.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __FeedbackEntity;
	private final mxbluecommons.proxies.Feedback FeedbackEntity;
	private final IMendixObject Entity;
	private final java.lang.String AttributeName;
	private final mxbluecommons.proxies.Enum_MessageType MessageType;
	private final com.mendix.systemwideinterfaces.javaactions.parameters.IStringTemplate Message;
	private final java.lang.String LogNodeName;

	public ProcessFeedbackMessage(
		IContext context,
		IMendixObject _feedbackEntity,
		IMendixObject _entity,
		java.lang.String _attributeName,
		java.lang.String _messageType,
		com.mendix.systemwideinterfaces.javaactions.parameters.IStringTemplate _message,
		java.lang.String _logNodeName
	)
	{
		super(context);
		this.__FeedbackEntity = _feedbackEntity;
		this.FeedbackEntity = _feedbackEntity == null ? null : mxbluecommons.proxies.Feedback.initialize(getContext(), _feedbackEntity);
		this.Entity = _entity;
		this.AttributeName = _attributeName;
		this.MessageType = _messageType == null ? null : mxbluecommons.proxies.Enum_MessageType.valueOf(_messageType);
		this.Message = _message;
		this.LogNodeName = _logNodeName;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE

    // Get logger.
    ILogNode log = Core.getLogger(this.LogNodeName);

    // Current counts.
    Integer cntError = this.FeedbackEntity.get_ErrorCount();

    // Validate input.
    _validateInput();

    // Get current status.
    String currentStatus = this.FeedbackEntity.getStatus().toString();

    // Set status (when needed) and add error count.
    switch (this.MessageType.toString()) {
      case "Critical":
        // Set status.
        this.FeedbackEntity.setStatus(mxbluecommons.proxies.Enum_FeedbackStatus.valueOf("Error"));
        break;
      case "Warning":
        // Set status, when current status is not error yet. (error is higer!)
        if (currentStatus != "Error") {
          this.FeedbackEntity.setStatus(mxbluecommons.proxies.Enum_FeedbackStatus.valueOf("Warning"));
        }
        break;
      case "Debug":
        break;
      case "Error":
        // Set status.
        this.FeedbackEntity.setStatus(mxbluecommons.proxies.Enum_FeedbackStatus.valueOf("Error"));
        // Add error count.
        this.FeedbackEntity.set_ErrorCount(cntError + 1);
        break;
      case "Trace":
        break;
      case "Information":
      case "Info":
      default:
        break;
    }

    // Instantiate Message.
    IMendixObject msg = Core.instantiate(getContext(), "MxBlueCommons.Message");

    // Set values.
    msg.setValue(getContext(), "Message", this.Message.toString());
    msg.setValue(getContext(), "MessageType", this.MessageType.toString());
    msg.setValue(getContext(), "Processed", true);
    msg.setValue(
      getContext(),
      "MxBlueCommons.Message_Feedback",
      this.FeedbackEntity.getMendixObject().getId()
    );

    // Should we show it on screen (validation feedback)?
    if (this.FeedbackEntity.getOnScreen()) {
      // Create data validation info
      DataValidationInfo dvi = new DataValidationInfo(
        this.Entity.getId().toLong()
      );

      // Add errir field.
      dvi.addErrorField(this.AttributeName, this.Message.toString());

      // Add validation feedback.
      this.addDataValidationFeedback(dvi);
    }

    // Should we show it in the console?
    if (this.FeedbackEntity.getInConsole()) {
      // Log message according to MessageType.
      switch (this.MessageType.toString()) {
        case "Critical":
          log.critical(this.Message.toString());
          break;
        case "Warning":
          log.warn(this.Message.toString());
          break;
        case "Debug":
          log.debug(this.Message.toString());
          break;
        case "Error":
          log.error(this.Message.toString());
          break;
        case "Trace":
          log.trace(this.Message.toString());
          break;
        case "Information":
        case "Info":
        default:
          log.info(this.Message.toString());
          break;
      }
    }

    // Return.
    return null;
    //throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ProcessFeedbackMessage";
	}

	// BEGIN EXTRA CODE

  // Function to validate input.
  private java.lang.Void _validateInput() throws Exception {
    // Check Message.
    if (this.Message == null) {
      throw new com.mendix.systemwideinterfaces.MendixRuntimeException(
        "Message is required."
      );
    }

    // Check MessageType.
    if (this.MessageType == null) {
      throw new com.mendix.systemwideinterfaces.MendixRuntimeException(
        "MessageType is required."
      );
    }

    // Check ShowOnScreen.
    if (this.FeedbackEntity.getOnScreen()) {
      // Check Entity.
      if (this.Entity == null) {
        throw new com.mendix.systemwideinterfaces.MendixRuntimeException(
          "Entity is required when ShowOnScreen is true."
        );
      }

      // Check AttributeName.
      if (this.AttributeName == null) {
        throw new com.mendix.systemwideinterfaces.MendixRuntimeException(
          "AttributeName is required when ShowOnScreen is true."
        );
      }
    }

    // Check ShowInConsole.
    if (this.FeedbackEntity.getInConsole()) {
      // Check LogNodeName.
      if (this.LogNodeName == null) {
        throw new com.mendix.systemwideinterfaces.MendixRuntimeException(
          "LogNodeName is required when ShowInConsole is true."
        );
      }
    }

    // Return.
    return null;
  }
	// END EXTRA CODE
}
