// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxbluecommons.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * XPath should have something like:
 * 
 * SUM(//Module.Entity.Attribute)
 */
public class RetrieveAggregateXpathAsDouble extends UserAction<java.math.BigDecimal>
{
	private final java.lang.String Xpath;

	public RetrieveAggregateXpathAsDouble(
		IContext context,
		java.lang.String _xpath
	)
	{
		super(context);
		this.Xpath = _xpath;
	}

	@java.lang.Override
	public java.math.BigDecimal executeAction() throws Exception
	{
		// BEGIN USER CODE

		// When going to Mx9+ only, we can use createXPathQuery!
		
		// Get double.
		java.lang.Double dbl = Core.retrieveXPathQueryAggregateAsyncDouble(getContext(), this.Xpath).get();

		// Return BigDecimal.
		return new java.math.BigDecimal(dbl);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "RetrieveAggregateXpathAsDouble";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
