// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxbluecommons.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * XPath should have something like:
 * 
 * COUNT(//Module.Entity)
 */
public class RetrieveAggregateXpathAsLong extends UserAction<java.lang.Long>
{
	private final java.lang.String Xpath;

	public RetrieveAggregateXpathAsLong(
		IContext context,
		java.lang.String _xpath
	)
	{
		super(context);
		this.Xpath = _xpath;
	}

	@java.lang.Override
	public java.lang.Long executeAction() throws Exception
	{
		// BEGIN USER CODE

		// When going to Mx9+ only, we can use createXPathQuery!
		
		// Get Long.
		java.lang.Long lng = Core.retrieveXPathQueryAggregateAsync(getContext(), this.Xpath).get();
		
		// Return long.
		return lng;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "RetrieveAggregateXpathAsLong";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
