// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxbluecommons.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.datastorage.XPathQuery;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Enter the complete xPath, including the entity to search for.
 * 
 * //[Module].[Entity][Active=true()]
 * 
 * like: 
 * 
 * //MyFirstModule.SomeEntity[Active=true()]
 * 
 * When offset/amount is not needed, set it to empty.
 * 
 * Create a list of XPathSorting to add sorting to the list.
 */
public class RetrieveAdvancedXpath extends UserAction<java.util.List<IMendixObject>>
{
	private final java.lang.String Xpath;
	private final java.lang.String ResultEntityType;
	private final java.lang.Long Offset;
	private final java.lang.Long Amount;
	/** @deprecated use com.mendix.utils.ListUtils.map(Sorting, com.mendix.systemwideinterfaces.core.IEntityProxy::getMendixObject) instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final java.util.List<IMendixObject> __Sorting;
	private final java.util.List<mxbluecommons.proxies.XPathSorting> Sorting;

	public RetrieveAdvancedXpath(
		IContext context,
		java.lang.String _xpath,
		java.lang.String _resultEntityType,
		java.lang.Long _offset,
		java.lang.Long _amount,
		java.util.List<IMendixObject> _sorting
	)
	{
		super(context);
		this.Xpath = _xpath;
		this.ResultEntityType = _resultEntityType;
		this.Offset = _offset;
		this.Amount = _amount;
		this.__Sorting = _sorting;
		this.Sorting = java.util.Optional.ofNullable(_sorting)
			.orElse(java.util.Collections.emptyList())
			.stream()
			.map(sortingElement -> mxbluecommons.proxies.XPathSorting.initialize(getContext(), sortingElement))
			.collect(java.util.stream.Collectors.toList());
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE

		// Result.
		java.util.List<IMendixObject> result = null;

		// Create XPath query (builder).
		XPathQuery query = Core.createXPathQuery(this.Xpath);

		ILogNode logger = Core.getLogger("Testing");

		// Check offset.
		if (this.Offset != null) {

			// Add offset.
			query.setOffset(this.Offset.intValue());
		}

		// Check amount.
		if (this.Amount != null) {

			// Set amount.
			query.setAmount(this.Amount.intValue());
		}
		
		// Loop through sorting list.
		for(mxbluecommons.proxies.XPathSorting srt : this.Sorting) {
			
			// Add sort.
			query.addSort(srt.getAttributeName(), srt.getAscending());
		}

		// Get result.
		result = query.execute(getContext());

		// Check result.
		if (!result.isEmpty() &&!result.get(0).getMetaObject().getName().equals(this.ResultEntityType)) {
			throw new MendixRuntimeException(String.format("Unexpected result entity: %s vs %s:",
				result.get(0).getMetaObject().getName(), this.ResultEntityType));
		}

		// Return.
		return result;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "RetrieveAdvancedXpath";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
