// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxbluecommons.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.IMendixObjectMember;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Set an attribute with an composed attribute name.
 */
public class SetAttributeString extends UserAction<java.lang.Boolean>
{
	private final IMendixObject entity;
	private final java.lang.String member;
	private final java.lang.String value;

	public SetAttributeString(
		IContext context,
		IMendixObject _entity,
		java.lang.String _member,
		java.lang.String _value
	)
	{
		super(context);
		this.entity = _entity;
		this.member = _member;
		this.value = _value;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE


IMendixObjectMember m = this.entity.getMember(this.getContext(), this.member);

		m.setValue(this.getContext(), m.getValueFromString(this.value));

		return true;
		//throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetAttributeString";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
