// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxbluecommons.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.meta.IMetaEnumValue;
import com.mendix.systemwideinterfaces.core.meta.IMetaPrimitive;
import com.mendix.systemwideinterfaces.core.meta.IMetaPrimitive.PrimitiveType;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Set an enum attribute to the value of a string (when the string has been found as an enum key).
 * 
 * - StringToParse : The actual string to parse.
 * - AttributeNameEnum: The name of the attribute with the enum.
 * - ObjectWithEnum: The object that has the enum as an attribute,
 */
public class StringToEnum extends UserAction<java.lang.Boolean>
{
	private final java.lang.String StringToParse;
	private final java.lang.String AttributeNameEnum;
	private final IMendixObject ObjectWithEnum;

	public StringToEnum(
		IContext context,
		java.lang.String _stringToParse,
		java.lang.String _attributeNameEnum,
		IMendixObject _objectWithEnum
	)
	{
		super(context);
		this.StringToParse = _stringToParse;
		this.AttributeNameEnum = _attributeNameEnum;
		this.ObjectWithEnum = _objectWithEnum;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		
		// Result.
		java.lang.Boolean result = false;

		// Find enum in object.
		if (this.ObjectWithEnum.getMember(getContext(), this.AttributeNameEnum) != null) {

			// Find enum in meta model.
			for (IMetaPrimitive metaPrim : this.ObjectWithEnum.getMetaObject().getMetaPrimitives()) {

				// Finnd by name and type.
				if (metaPrim.getType() == PrimitiveType.Enum && metaPrim.getName().equals(this.AttributeNameEnum)) {

					// Get possible values.
					for (IMetaEnumValue metaEnumVal : metaPrim.getEnumValues()) {

						// Did we find it?
						if (metaEnumVal.getIdentifier().equals(this.StringToParse)) {

							// Set value.
							this.ObjectWithEnum.setValue(getContext(), this.AttributeNameEnum, metaEnumVal.getIdentifier());

							// Set result.
							result = true;

							// Break out of loop. We're done.
							break;
						}
					}
				}
			}
		}

		// Return.
		return result;

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "StringToEnum";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
